### ISSUE TITLE
Canary rollout upgrade

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#2371]
This is a _shell_ issue, that gathers the technical gaps, identified to implement Camel K operator canary rollout upgrade:

- [x]  Support resources _scoping_, _locking_/_handover_: #1943
  - [x] Upgrade controller-runtime to version v0.9.0
  - [x] Use selectors support from controller-runtime: kubernetes-sigs/controller-runtime#1435
- [x] Improve multiple operators topology: #2177
- [x] Add support for Integration Deployment strategy: #2256
- [ ] Report the [Upgradable](https://olm.operatorframework.io/docs/advanced-tasks/communicating-operator-conditions-to-olm/#upgradeable) Condition to OLM
- [ ] Complement existing upgrade e2e tests to cover canary rollout use cases

The implementation should work equally for both OLM and standalone (`kamel install` or `kustomize`) installation modes.

**Comment by lburgazzoli** [comment]
Relates to https://github.com/apache/camel-k/issues/3397#issuecomment-1735525398
